const $=document.getElementById('root');
const icons={user:'☻',bell:'♧',search:'⌕',qr:'▦',plus:'＋',swap:'↔',card:'▭',percent:'%',info:'ⓘ',clock:'◷',chat:'▱',more:'•••',eye:'⌧',door:'⇱',map:'♙',back:'←',cal:'▣',cash:'▣',lock:'▣',gear:'⚙',shield:'♥',face:'⌘',del:'⌫'};
function logo(){return'<div class="logo">⚒</div>'}function ic(x,c=''){return`<div class="ico ${c}">${icons[x]||x}</div>`}function round(x,dot=''){return`<button class="round">${icons[x]}${dot?'<b></b>':''}</button>`}
function show(p){$.innerHTML=p;bind()}
function splash(){show(`<div class="splash">${logo()}</div>`);setTimeout(pin,900)}
function pin(){show(`<main class="pin"><div class="bar">${round('door')}<span></span>${round('map')}${round('chat')}</div><h1>Введите<br>короткий код</h1><div class="stars">* * * *</div><div class="keypad">${[1,2,3,4,5,6,7,8,9].map(n=>`<b>${n}</b>`).join('')}<span>${icons.face}</span><b data-go="home">0</b><span>${icons.del}</span></div></main>`)}
function home(sheet=false){show(`<main class="home"><section class="top card"><div class="bar"><button data-go="profile" class="round">${icons.user}<b></b></button><span></span>${round('bell')}${round('search')}</div><p class="muted">Всего по курсу ЦБ</p><h1>8,07 ₽ <span>${icons.eye}</span></h1><button class="pill">Деньги на графике ›</button><div class="actions"><div>${ic('qr','dark')}<p>Оплата<br>по QR</p></div><div>${ic('<span class="play">▶</span>')}<p>По номеру<br>телефона</p></div><div>${ic('swap')}<p>Между<br>счетами</p></div><div>${ic('plus')}<p>Из другого<br>банка</p></div></div></section><div class="stories"><div>Как снять<br>наличные<br>без карты</div><div>Куда поехать,<br>кроме моря<br>и дачи</div><div>Как защитить<br>деньги<br>в поездке</div><div>Вам позво<br>оператор?</div></div><section class="product card"><div class="row">${icons.card}<div><h2>62,21 ₽</h2><p>Mir 110 Credit *6094</p><div class="miniCard">3107<br><b>МИР</b></div></div></div><p class="hint">${icons.info} Внесите минимальный платеж до 11 августа 18:00 по МСК</p><button data-sheet="1" class="pay">Внести 20 127,49 ₽</button></section>${['0 ₽|Текущий счет *0195','0 ₽|Текущий счет *9532','0 $|Текущий счет *2613','0 ₽|Выгода *5717'].map(x=>`<section class="line">${icons.card}<div><h2>${x.split('|')[0]}</h2><p>${x.split('|')[1]}</p></div></section>`).join('')}<section data-go="loan" class="line loan">${icons.percent}<div><h2>19 573,54 ₽ до 8 августа</h2><p>Потребительский кредит 295 419,65 ₽</p><small>${icons.info} 8,07 ₽ на счете</small></div></section><section class="buttons card"><button>Все продукты</button><button>Открыть новый продукт</button></section></main>${nav()}${sheet?sheetHtml():''}`)}
function nav(){return`<nav><b>${logo()}Главный</b><span>${icons.clock}История</span><span>${icons.swap}Платежи</span><span>${icons.chat}Чат</span><span>${icons.more}Еще<i>28</i></span></nav>`}
function sheetHtml(){return`<div class="shade"><div class="sheet"><i></i><h1>Откуда пополнить счет?</h1><div class="banks"><div><em class="sber">✓</em><b>Сбербанк</b></div><div><em class="tbank">T</em><b>Т-Банк</b></div><div><em class="vtb">▰</em><b>ВТБ</b></div><div>${ic('⌂')}<b>Из другого<br>банка</b></div></div><p>Без комиссии между своими счетами — до 30 млн ₽ в месяц <span class="play">▶</span></p><p>Еще варианты</p><div class="option">${ic('swap')}Со своего счета в Райффайзен Банке</div><div class="option">${ic('card')}С другой карты</div></div></div>`}
function loan(){show(`<main class="loanPage"><button data-go="home" class="back">${icons.back}</button><h1>19 573,54 ₽</h1><p>Следующий платеж 8 августа</p><div class="actions three"><div>${ic('cal')}<p>График<br>платежей</p></div><div>${ic('plus')}<p>Пополнить<br>счет</p></div><div>${ic('cash')}<p>Погасить<br>досрочно</p></div></div><section class="card row">${ic('₽')}<div><h2>8,07 ₽ на счете</h2><p>Текущий *9949</p></div><b>›</b></section>${block('Осталось выплатить','<button>Еще</button><h2>298 137,19 ₽</h2><div class="progress"><b></b></div><p><span>1 311 427,18 ₽</span><span>из 1 609 564,37 ₽</span></p>')}${block('История','<button>Еще</button><p>10 июля, пятница</p><div class="row">'+ic('percent')+'<h3>Оплатили просроченную<br>задолженность</h3><h3>− 16 024,71 ₽</h3></div>')}${block('Другое',['Условия кредита|%','Кредитный договор|▣','Изменить дату платежа|▣','Платить с другого счета|₽','Взять паузу в выплатах|Ⅱ','Заказать справку|♜'].map(i=>`<div class="menu"><span>${i.split('|')[0]}</span><b>${i.split('|')[1]}</b></div>`).join(''))}</main>`)}function block(t,c){return`<section class="card block"><h1>${t}</h1>${c}</section>`}
function profile(){show(`<main class="profile"><div class="art"><button data-go="home">${icons.back}</button><span>${icons.door}</span></div><section><h1>Андрей</h1><div class="actions three"><div>${ic('user')}<p>Личные данные</p></div><div>${ic('gear')}<p>Настройки</p></div><div>${ic('lock')}<p>Блокировка денег</p></div></div><div class="safe">${icons.shield}<div><h2>Всё для безопасности</h2><p>Пароль, короткий код, лимиты,<br>защита от мошенников</p></div><b>›</b></div><div class="tiles"><div>ϟ<h2>Подписка</h2><p>Одна Подписка —<br>максимум выгоды</p></div><div>♦<h2>Premium<br>Banking</h2><p>Привилегии для вас</p></div></div></section></main>`)}
function bind(){document.querySelectorAll('[data-go]').forEach(el=>el.onclick=()=>({home,loan,profile}[el.dataset.go]()));document.querySelectorAll('[data-sheet]').forEach(el=>el.onclick=()=>home(true));document.querySelector('.shade')?.addEventListener('click',e=>{if(e.target.className==='shade')home(false)})}if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');splash();
